"use client";
import { useState } from "react";
const metrics=[
["GHG-S1","Scope 1 GHG emissions","tCO2e","CALCULATED","ORGANIZATIONAL","NOT AVAILABLE","IFRS S2 · GHG Protocol"],
["GHG-S2","Scope 2 GHG emissions","tCO2e","CALCULATED","ORGANIZATIONAL","NOT AVAILABLE","IFRS S2 · GHG Protocol"],
["GHG-S3","Scope 3 GHG emissions","tCO2e","CALCULATED","VALUE_CHAIN","NOT AVAILABLE","IFRS S2 · GHG Protocol"],
["ENV-RF","Rainfall observation","mm","OBSERVATION","SITE","GATED","Environmental DMRV"],
["CLM-01","Climate-risk disclosure mapping","status","DISCLOSURE_DERIVED","PROJECT","MAPPING PROFILE","IFRS S2"],
["ESRS-E1","Climate disclosure datapoint mapping","status","DISCLOSURE_DERIVED","PROJECT","MAPPING PROFILE","ESRS E1"]
];
const controls=["Control effectiveness","Exception state","Evidence lineage","DMRV reconciliation","QMS / custody","Anchor integrity","CAPA","Independent review","Claims boundary","Standards mapping"];
const states=["SIGNAL","REPORTABLE","VALIDATED","VERIFIED","ANCHORED","ASSURANCE REVIEW","HOLD"];
export default function Assurance(){
 const [tab,setTab]=useState("Dashboard"),[all,setAll]=useState(false);
 return <main className="a"><style>{\`
 body{margin:0;background:#07100d;color:#e9f0ec;font-family:Inter,system-ui,sans-serif}.a{min-height:100vh;max-width:1440px;margin:auto;padding:32px}.top{display:flex;justify-content:space-between;gap:20px}.ey{font-size:11px;letter-spacing:.14em;color:#8ea59b}.top h1{font-size:34px;margin:8px 0}.muted{color:#91a39b;line-height:1.5}.badge{border:1px solid #34463f;border-radius:999px;padding:6px 10px;font-size:11px}.warn{border-color:#7d6940;color:#e2c887}.tabs{display:flex;gap:8px;margin:22px 0;flex-wrap:wrap}.tab{background:#0c1713;color:#9eb0a7;border:1px solid #1d3028;border-radius:10px;padding:10px 13px;cursor:pointer}.active{color:#fff;border-color:#71907f}.grid{display:grid;grid-template-columns:1.5fr 1fr;gap:16px}.card{background:#0c1713;border:1px solid #1d3028;border-radius:16px;padding:20px}.card h2{font-size:16px;margin:0 0 8px}.list{display:grid;gap:8px}.row{display:flex;justify-content:space-between;gap:10px;border:1px solid #1d3028;border-radius:10px;padding:12px}.row small{display:block;color:#8ea59b;margin-top:5px}.metric{display:grid;grid-template-columns:1.5fr .6fr .8fr .9fr;gap:10px;padding:12px 0;border-top:1px solid #1d3028;font-size:13px}.metric small{display:block;color:#8ea59b;margin-top:4px}.callout{margin-top:16px;padding:14px;border:1px dashed #56675f;border-radius:12px}.footer{margin-top:18px;color:#71847b;font-size:12px}@media(max-width:900px){.a{padding:18px}.grid{grid-template-columns:1fr}.metric{grid-template-columns:1fr 1fr}.top{display:block}}\`}</style>
 <div className="top"><div><div className="ey">BLUE-ETHER OS · M-1 · S9.3</div><h1>Assurance Dashboard & Audit Pack</h1><div className="muted">Standards-aware climate/ESG data conformity surface. <b>Alignment is not certification.</b></div></div><div className="badge warn">PHYSICAL STATUS · NOT RELEASED</div></div>
 <div className="tabs">{["Dashboard","Climate / GHG","ESRS E1","Audit Pack"].map(t=><button key={t} className={"tab "+(tab===t?"active":"")} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==="Dashboard"&&<><div className="grid"><section className="card"><h2>Control effectiveness & evidence state</h2><div className="muted">Operational control signals remain separate from evidence conclusions.</div><div className="list" style={{marginTop:12}}>{controls.map((x,i)=><div className="row" key={x}><div><b>{x}</b><small>{i<3?"LINKED / CONTROLLED":i<8?"REVIEW SURFACE":"MAPPING SURFACE"}</small></div><span className="badge">{i<8?"TRACKED":"PROFILE"}</span></div>)}</div></section><section className="card"><h2>Evidence-state ladder</h2><div className="list">{states.map(s=><div className="row" key={s}><b>{s}</b><span className="muted">{s==="HOLD"?"Promotion blocked":"Explicit evidence context required"}</span></div>)}</div><div className="callout">DASHBOARD ≠ EVIDENCE · AUDIT PACK ≠ CERTIFICATION · ANCHOR ≠ ENVIRONMENTAL TRUTH</div></section></div><section className="card" style={{marginTop:16}}><h2>Climate / ESG metric registry</h2><div className="metric" style={{borderTop:0}}><b>Metric</b><b>Unit</b><b>Data class</b><b>Boundary / status</b></div>{metrics.slice(0,all?metrics.length:4).map(m=><div className="metric" key={m[0]}><div><b>{m[1]}</b><small>{m[0]} · {m[6]}</small></div><div>{m[2]}</div><div>{m[3]}</div><div>{m[4]}<small>{m[5]}</small></div></div>)}<button className="tab" onClick={()=>setAll(!all)}>{all?"Show core metrics":"Show all registry fields"}</button></section></>}
 {tab==="Climate / GHG"&&<div className="grid"><section className="card"><h2>GHG Protocol / IFRS S2 alignment</h2><div className="list">{["Organizational boundary","Operational boundary","Scope 1","Scope 2","Scope 3","Activity data","Emission factors","Calculation method","Uncertainty / estimation","Base year / restatement","Evidence references","Methodology version"].map(x=><div className="row" key={x}><b>{x}</b><span className="muted">Required context before disclosure-ready status</span></div>)}</div></section><section className="card"><h2>Disclosure boundary</h2><p className="muted">The system records measurement basis, inputs and assumptions rather than collapsing them into a single impact score. Missing evidence remains missing.</p><div className="callout">GHG CLAIMS REQUIRE SCOPE + BOUNDARY + METHOD + SOURCE + PERIOD + UNIT + EVIDENCE.</div></section></div>}
 {tab==="ESRS E1"&&<section className="card"><h2>ESRS E1 mapping profile</h2><p className="muted">Transition plan, policies, actions/resources, targets, energy/GHG emissions, removals/credits where applicable, internal carbon pricing where applicable, and anticipated financial effects where applicable are represented as mapping domains.</p><div className="grid">{["Transition plan","Policies","Actions / resources","Targets","Energy + GHG emissions","Removals / credits","Internal carbon pricing","Anticipated financial effects"].map(x=><div className="row" key={x}><b>{x}</b><span className="muted">MAPPING PROFILE · jurisdictional applicability must be resolved</span></div>)}</div><div className="callout">2026 EFRAG DRAFT DATAPOINTS ARE NON-AUTHORITATIVE SUPPORTING MATERIAL UNTIL FINAL PUBLICATION.</div></section>}
 {tab==="Audit Pack"&&<div className="grid"><section className="card"><h2>Audit pack index</h2><div className="list">{["Control effectiveness matrix","Exception register","Evidence lineage","DMRV reconciliation","QMS / custody status","Anchor register","Change / version register","CAPA register","Independent review log","Claim review","Standards mapping ledger"].map(x=><div className="row" key={x}><b>{x}</b><span className="badge">INDEXED</span></div>)}</div></section><section className="card"><h2>Fail-closed gates</h2><div className="list">{["Missing evidence references","Broken lineage","Unresolved material exception","Missing reviewer authority/conflict record","Stale review period","GHG scope without boundary/method context","Uncontrolled methodology version","Unsupported claim promotion"].map(x=><div className="row" key={x}><b>{x}</b><span className="badge warn">HOLD</span></div>)}</div></section></div>}
 <div className="footer"><a href="/">← Return to Command Center</a> · Standards mapping is an implementation aid, not legal/accounting/audit advice.</div>
 </main>
}