"use client";
import { useMemo, useState } from "react";
import WebGLGlobe from "./components/WebGLGlobe";

const nav=["Command Center","Project Scope","Production Control","Controlled Pilot","Conformance Review","Replication Readiness","Multisite Execution","Scale Readiness","Governed Scale","Continuous Assurance","Exception Automation","Assurance Dashboard","Independent Assurance","Global Lagos","Harvest Intelligence","Evidence & DMRV","ESG / GHG","Investor Room"];
const productionStages=[["M-1","Institutional foundation","IMPLEMENTED"],["S6A","Blockchain evidence","CONTROLLED"],["S6B","Builder / grant evidence","READY"],["S6C","Lagos physical validation","GATED"],["POST-S6C","Release + public verification","GATED"],["S7","Monitoring + assurance","IMPLEMENTED"],["S8","Controlled multisite expansion","IMPLEMENTED"],["S8.1","Site onboarding + local authorization","CURRENT"]];
const operatingLadder=["DESIGNED","IMPLEMENTED","INTEGRATION_READY","CONTROLLED_TEST","REPORTABLE","VALIDATED","VERIFIED","ANCHORED","RELEASED"];
const scopeDomains=["Rain harvesting + controlled collection","Premium-condition evidence","Water/QMS + batch/seal provenance","Environmental DMRV + ESG/GHG","Blockchain evidence integrity","Investor / public verification"];
const gates=["Source registry","Forecast snapshot","Measured telemetry","Rain event","Collection + first flush","Water/QMS","Batch + bottle seal","Evidence root","DMRV review","Blockchain proof"];
const venues=[
 ["AGEGE","Orile-Agege"],["AJEROMI-IFELODUN","Ifelodun"],["ALIMOSHO","Ayobo-Ipaja · Egbe-Idimu · Igando-Ikotun · Mosan Okunola"],["AMUWO-ODOFIN","Oriade"],["APAPA","Apapa-Iganmu"],["BADAGRY","Badagry West · Olorunda"],["EPE","Eredo · Ikosi-Ejinrin"],["ETI-OSA","Eti-Osa East · Iru Victoria Island · Ikoyi Obalende"],["IBEJU-LEKKI","Lekki"],["IFAKO-IJAIYE","Ojokoro · Agbado/Oke-Odo"],["IKEJA","Ojodu · Onigbongbo"],["IKORODU","Ikorodu North · Ikorodu West · Imota · Ijede · Igbogbo-Baiyeku"],["KOSOFE","Ikosi-Isheri · Agboyi-Ketu"],["LAGOS ISLAND","Lagos Island East"],["LAGOS MAINLAND","Yaba"],["MUSHIN","Odi-Olowo/Ojuwoye"],["OJO","Oto-Awori · Iba"],["SOMOLU","Bariga"],["OSHODI-ISOLO","Isolo · Ejigbo"],["SURULERE","Coker-Aguda · Itire-Ikate"]
];
const institutional=["Governor's Office","Governor's Residence · generalized public site","NCF Lekki Conservation Centre"];
const indicators=[
 ["Rainfall","Open-Meteo","Authorized local gauge","FORECAST ↔ OBSERVED"],["Atmospheric NO₂","CAMS/Open-Meteo","Sentinel-5P / TROPOMI","MODEL ↔ SATELLITE"],["SO₂ / O₃ / CO","CAMS/Open-Meteo","Sentinel-5P / TROPOMI","MODEL ↔ SATELLITE"],["PM2.5 / PM10","Air-quality model","Authorized local sensor","MODEL ↔ OBSERVED"],["Temperature / humidity / wind","Open-Meteo","Authorized local station","MODEL ↔ OBSERVED"],["Solar radiation","Open-Meteo","Satellite-derived dataset","MODEL ↔ SATELLITE"]
];
const evidence=[
 ["BE-OMI-0001","Rainfall observation","VALIDATED","Open-Meteo · provenance complete","ANCHOR PENDING"],["BE-OMI-0002","Atmospheric NO₂","REPORTABLE","Model + Sentinel cross-check","REVIEW REQUIRED"],["BE-OMI-0003","Controlled scenario","SIMULATED","Model-only demonstration","NOT PRODUCTION"],["VID-GL-0001","Collection video manifest","UNVERIFIED","Future field-validation boundary","NOT ANCHORED"]
];
const feeds=["Rainfall telemetry","Air-quality observations","Satellite cross-checks","Harvest operation video","Post-collection custody video"];

export default function Home(){
 const [active,setActive]=useState("Command Center"); const [demo,setDemo]=useState(false); const [selected,setSelected]=useState<string|null>(null); const global=active==="Global Lagos";
 const control=active==="Production Control";
 const pilot=active==="Controlled Pilot";
 const conformance=active==="Conformance Review";
 const replication=active==="Replication Readiness";
 const multisite=active==="Multisite Execution";
 const scale=active==="Scale Readiness";
 const governed=active==="Governed Scale";
 const assurance=active==="Continuous Assurance";
 const exceptions=active==="Exception Automation";
 const assuranceDashboard=active==="Assurance Dashboard";
 const independentAssurance=active==="Independent Assurance";
 const scope=active==="Project Scope";
 const selectedVenue=useMemo(()=>selected?([...venues.map((v,i)=>({id:String(i+1).padStart(2,"0"),name:v[0],detail:v[1]})),...institutional.map((v,i)=>({id:String(38+i),name:v,detail:"Institutional / environmental reference venue"}))].find(v=>v.id===selected)):null,[selected]);
 const go=(n:string)=>{if(n==="Assurance Dashboard"){window.location.href="/assurance";return;}if(n==="Independent Assurance"){window.location.href="/assurance-readiness";return;}setActive(n);window.scrollTo({top:0,behavior:"smooth"})};
 return <div className="shell">
 <header className="topbar"><div className="brand"><div className="mark">B</div><div>BLUE-ETHER <span>OS</span></div></div><div className="top-actions"><button className={global?"top-link active":"top-link"} onClick={()=>go("Global Lagos")}>◎ Global Lagos</button><div className="status">M-1 · S9.3 CURRENT · EVIDENCE-FIRST</div></div></header>
 <div className="layout"><aside className="nav">{nav.map(n=><button key={n} className={active===n?"active":""} onClick={()=>go(n)}>{n}</button>)}</aside><main className="main">
 {!global&&!scope&&!control&&<section className="hero"><div className="panel hero-copy"><div className="eyebrow">37-LCDA WATER + ENVIRONMENTAL DATA OPERATING SYSTEM</div><h1>Rain becomes an investable evidence stream.</h1><p>Blue-Ether OS turns environmental observations into provenance-rich evidence packages. Forecasts, models, satellite observations and measured data remain explicitly distinct until their quality and reconciliation rules are satisfied.</p><div className="actions"><button className="primary" onClick={()=>go("Global Lagos")}>Explore Global Lagos Pilot</button><button className="secondary" onClick={()=>setDemo(!demo)}>{demo?"Hide controlled scenario":"Run controlled scenario"}</button><button className="secondary" onClick={()=>go("Investor Room")}>Open investor room</button></div>{demo&&<div className="scenario">CONTROLLED SIMULATION · Source → observation → QA → evidence root. No live production, harvest or sale claim.</div>}</div><div className="panel globe"><WebGLGlobe/><div className="globe-overlay"><span className="badge verified">WEBGL · VISUALIZATION</span><div><strong>Lagos environmental evidence surface</strong><div className="muted">Visualization is not evidence. Authoritative status comes from immutable evidence records.</div></div></div></div></section>}
 {!global&&!scope&&!control&&<section className="panel section control-strip"><SectionTitle title="Production control" sub="Frontend status mirrors the controlled production definition; UI state does not create empirical evidence."/><div className="control-grid">{productionStages.map(([id,label,state])=><button key={id} className="control-card" onClick={()=>go(id==="S8.1"?"Production Control":id==="S8"?"Production Control":"Command Center")}><span>{id}</span><strong>{label}</strong><em>{state}</em></button>)}</div><div className="ladder">{operatingLadder.map((x,i)=><span key={x} className={i<3?"ladder-on":""}>{x}</span>)}</div></section>}
 {scope&&<section className="panel section scope-view"><SectionTitle title="Project Scope & Evidence Contract" sub="The frontend is the operational interpretation of the production framework, not a substitute for it."/><div className="scope-grid"><div><h3>What the system does</h3><p>OMI-OJO / Blue-Ether converts rainfall, atmospheric and operational observations into provenance-rich DMRV evidence for controlled rainwater harvesting, premium-condition review, ESG/GHG reporting and public/investor verification.</p><h3>What the system does not assume</h3><p>Forecasts are not observations; administrative nodes are not physical sites; blockchain anchors do not prove environmental truth; technical readiness does not authorize product release.</p></div><div><h3>Structured domains</h3>{scopeDomains.map(x=><div className="scope-row" key={x}><span>✓</span>{x}</div>)}<div className="scenario">Current physical status: NOT RELEASED · Project token: DEFERRED · Funding award: NOT AWARDED</div></div></div></section>}
 {control&&<section className="panel section control-view"><SectionTitle title="Production Control / S8.1" sub="Site onboarding and local authorization — current controlled expansion procedure."/><div className="control-banner"><div><div className="eyebrow">CURRENT GATE</div><h2>S8.1 · SITE ONBOARDING + LOCAL AUTHORIZATION</h2><p>Admission of a proposed physical site requires identity, geospatial verification where applicable, local authorization, accountable operator/collector, regulatory scope, QMS pathway, provider mappings, unique DMRV identity and controlled anchor configuration.</p></div><span className="badge pending-b">EMPIRICAL EVIDENCE PENDING</span></div><div className="gate-grid"><GateStep n="01" t="Define site" b="Unique site/proposal ID and node classification."/><GateStep n="02" t="Verify identity" b="Geospatial verification before physical classification."/><GateStep n="03" t="Authorize" b="Record authority, scope and validity before collection."/><GateStep n="04" t="Operationalize" b="Operator, collector, QMS, providers and DMRV controls."/><GateStep n="05" t="Admit" b="Decision authority, timestamp and integrity digest."/><GateStep n="06" t="Advance" b="S8.2 controlled pilot only after admission controls pass."/></div><div className="scenario">FAIL-CLOSED: site onboarding does not mean harvest occurred, water was tested, a batch was produced, or product was released.</div></section>}
 {pilot&&<section className="panel section control-view"><SectionTitle title="Controlled Pilot / S8.2" sub="Site operational readiness and controlled-pilot sequence."/><div className="control-banner"><div><div className="eyebrow">CURRENT GATE</div><h2>S8.2 · SITE OPERATIONAL READINESS</h2><p>An admitted site must pass authorization, operator, equipment, rain-event, first-flush, collection, custody/QMS, DMRV and hold/rollback controls before a controlled pilot is considered ready.</p></div><span className="badge pending-b">PHYSICAL EVIDENCE PENDING</span></div><div className="gate-grid"><GateStep n="01" t="Admission" b="S8.1 site identity, authorization and accountability."/><GateStep n="02" t="Site readiness" b="Equipment, collector and geospatial controls."/><GateStep n="03" t="Rain watch" b="Source-provenanced event monitoring."/><GateStep n="04" t="First flush" b="Controlled diversion before collection."/><GateStep n="05" t="Collection + custody" b="Capture, sample identity and chain of custody."/><GateStep n="06" t="QMS + DMRV" b="Laboratory handoff and evidence package."/><GateStep n="07" t="Review + closeout" b="Conformance review before S8.3."/><GateStep n="08" t="Hold / rollback" b="Stop on material deviation or unresolved conflict."/></div><div className="scenario">READINESS ≠ HARVEST · QMS READINESS ≠ LAB RESULT · DMRV PACKAGE ≠ VERIFICATION · PILOT ≠ PRODUCT RELEASE</div></section>}
 {exceptions&&<section className="panel section control-view"><SectionTitle title="Exception Automation / S9.2" sub="Automated detection and escalation with human-controlled material decisions."/><div className="control-banner"><div><div className="eyebrow">CONTROL EFFECTIVENESS GATE</div><h2>S9.2 · EXCEPTION AUTOMATION</h2><p>Automated controls detect and route anomalies. Authorized humans retain severity, CAPA closure, suspension/resumption and claim decisions.</p></div><span className="badge pending-b">FAIL CLOSED</span></div><div className="gate-grid"><GateStep n="01" t="Detect" b="Schema, provenance, identity, custody, DMRV and anchor signals."/><GateStep n="02" t="Classify" b="Observation, minor, major or critical."/><GateStep n="03" t="Assign" b="Evidence scope and accountable owner."/><GateStep n="04" t="Contain" b="Protect affected scope from unsupported promotion."/><GateStep n="05" t="CAPA" b="Investigate, correct and document action."/><GateStep n="06" t="Review" b="Independent/effectiveness review where required."/><GateStep n="07" t="Close" b="Authorized closure with effectiveness evidence."/><GateStep n="08" t="Reopen / suspend" b="Persistent failure triggers renewed control action."/></div><div className="registry-row"><div><strong>Automation boundary</strong><div className="muted">AUTOMATION DETECTS · HUMANS AUTHORIZE MATERIAL DECISIONS</div></div><span className="badge pending-b">AUDIT TRAILED</span></div><div className="scenario">EXCEPTION AUTOMATION ≠ CERTIFICATION · CAPA CLOSURE ≠ PRODUCT RELEASE</div></section>}
 {assurance&&<section className="panel section control-view"><SectionTitle title="Continuous Assurance / S9.1" sub="Independent testing of whether governed-scale controls remain effective in operation."/><div className="control-banner"><div><div className="eyebrow">ASSURANCE GATE</div><h2>S9.1 · CONTROL EFFECTIVENESS</h2><p>Documentation shows a control exists; operating evidence shows it operated. Independent review tests effectiveness for a defined scope and period.</p></div><span className="badge pending-b">ASSURANCE ACTIVE</span></div><div className="gate-grid"><GateStep n="01" t="Inventory" b="Define control, owner, scope and review period."/><GateStep n="02" t="Signals" b="Collect operating evidence and reconciliation signals."/><GateStep n="03" t="Exceptions" b="Triage material conflicts and repeated failures."/><GateStep n="04" t="Attestation" b="Control owner records accountable attestation."/><GateStep n="05" t="Independent sample" b="Reviewer samples immutable evidence identifiers."/><GateStep n="06" t="Effectiveness" b="Effective, observations, improvement, ineffective or suspended."/><GateStep n="07" t="CAPA" b="Link remediation to affected evidence scope."/><GateStep n="08" t="Recertify" b="Repeat on defined cadence or after material change."/></div><div className="registry-row"><div><strong>Independence invariant</strong><div className="muted">OWNER ATTESTATION ≠ INDEPENDENT REVIEW · IMPLEMENTED ≠ EFFECTIVE</div></div><span className="badge pending-b">FAIL CLOSED</span></div><div className="scenario">CONTROL EFFECTIVENESS ≠ PREMIUM · ASSURANCE ≠ PRODUCT RELEASE</div></section>}
 {governed&&<section className="panel section control-view"><SectionTitle title="Governed Scale / S9" sub="Continuous assurance layer for controlled production-scale operation."/><div className="control-banner"><div><div className="eyebrow">GOVERNANCE GATE</div><h2>S9 · GOVERNED SCALE EXECUTION</h2><p>Scale operation remains subject to continuous DMRV reconciliation, QMS/custody assurance, change control, exception management, independent assurance and claim review.</p></div><span className="badge pending-b">CONTROLLED SCALE</span></div><div className="gate-grid"><GateStep n="01" t="Scope approval" b="Governed sites and obligations are explicit."/><GateStep n="02" t="Controlled execution" b="Approved operating controls remain active."/><GateStep n="03" t="Continuous DMRV" b="Source, provenance and reconciliation checks."/><GateStep n="04" t="QMS + custody" b="Measurement evidence remains traceable."/><GateStep n="05" t="Exceptions" b="Material failures enter HOLD / SUSPENDED."/><GateStep n="06" t="Independent assurance" b="Control effectiveness is periodically reviewed."/><GateStep n="07" t="Change control" b="Schema/model/control changes are versioned."/><GateStep n="08" t="Claims" b="Public and investor claims remain evidence-scoped."/></div><div className="registry-row"><div><strong>Continuous assurance invariant</strong><div className="muted">API HEALTH ≠ EVIDENCE · ANCHOR ≠ TRUTH · HISTORY IS NOT SILENTLY REWRITTEN</div></div><span className="badge pending-b">FAIL CLOSED</span></div><div className="scenario">GOVERNED SCALE ≠ PRODUCT RELEASE · CONTROLLED OPERATION ≠ ENVIRONMENTAL CERTIFICATION</div></section>}
 {scale&&<section className="panel section control-view"><SectionTitle title="Scale Readiness / S8.6" sub="Portfolio evidence consolidation with preserved site-level provenance and controlled aggregation."/><div className="control-banner"><div><div className="eyebrow">SCALE GATE</div><h2>S8.6 · MULTISITE EVIDENCE CONSOLIDATION</h2><p>Portfolio reporting indexes independently reviewed site evidence. It does not erase provenance, turn missing data into zero, or convert administrative coverage into physical harvest.</p></div><span className="badge pending-b">NOT RELEASED</span></div><div className="gate-grid"><GateStep n="01" t="Scope lock" b="Freeze portfolio membership and review period."/><GateStep n="02" t="Site outcomes" b="Import site decisions without overwriting them."/><GateStep n="03" t="Provenance" b="Retain source, timestamp, method and site identity."/><GateStep n="04" t="Evidence classes" b="Observed, forecast, modelled, satellite, calculated, proxy."/><GateStep n="05" t="Comparability" b="Check units, methods, periods and reporting scope."/><GateStep n="06" t="DMRV + anchors" b="Version drift and anchor integrity review."/><GateStep n="07" t="CAPA + claims" b="Exceptions remain visible; claims stay reproducible."/><GateStep n="08" t="Scale decision" b="Ready, conditional, hold or not ready."/></div><div className="registry-row"><div><strong>Aggregation invariant</strong><div className="muted">SITE PROVENANCE PRESERVED · MISSING ≠ ZERO · EVIDENCE CLASS PRESERVED</div></div><span className="badge pending-b">CONTROLLED SCALE</span></div><div className="scenario">SCALE READINESS ≠ PRODUCT RELEASE · AGGREGATE ≠ ENVIRONMENTAL TRUTH</div></section>}
 {multisite&&<section className="panel section control-view"><SectionTitle title="Multisite Execution / S8.5" sub="Controlled replication across independently admitted sites with isolated evidence domains."/><div className="control-banner"><div><div className="eyebrow">CURRENT CONTROL GATE</div><h2>S8.5 · MULTISITE EXECUTION</h2><p>Each site executes the approved field-to-DMRV chain independently. Portfolio review compares control conformance; it does not transfer environmental evidence between sites.</p></div><span className="badge pending-b">EXECUTION PENDING</span></div><div className="gate-grid"><GateStep n="01" t="Scope lock" b="Independent site identity and review scope."/><GateStep n="02" t="Authorization" b="Local authorization and accountable operator."/><GateStep n="03" t="Field execution" b="Inspection, rain watch, first flush, collection."/><GateStep n="04" t="Custody + QMS" b="Site-specific sample continuity and QMS."/><GateStep n="05" t="Site DMRV" b="Evidence package and provenance reconciliation."/><GateStep n="06" t="Independent review" b="Conformance decision for each site."/><GateStep n="07" t="Portfolio review" b="Compare controls without evidence transfer."/><GateStep n="08" t="Closeout" b="CAPA, hold, conditional or conforming outcome."/></div><div className="registry-row"><div><strong>Evidence isolation</strong><div className="muted">SITE A EVIDENCE ≠ SITE B EVIDENCE · EACH SITE RETAINS ITS OWN NAMESPACE</div></div><span className="badge pending-b">SITE-SCOPED</span></div><div className="scenario">MULTISITE EXECUTION ≠ MULTISITE HARVEST CLAIM · COMPARISON ≠ EVIDENCE TRANSFER</div></section>}
 {replication&&<section className="panel section control-view"><SectionTitle title="Replication Readiness / S8.4" sub="Multisite control conformance without copying environmental evidence between sites."/><div className="control-banner"><div><div className="eyebrow">NEXT CONTROL GATE</div><h2>S8.4 · MULTISITE CONFORMANCE</h2><p>Replication instantiates the control framework at an independently identified site. It does not transfer rainfall, harvest, laboratory, premium or regulatory evidence from another site.</p></div><span className="badge pending-b">NOT RELEASED</span></div><div className="gate-grid"><GateStep n="01" t="Site identity" b="Independent physical identity and authorization."/><GateStep n="02" t="Operator + equipment" b="Accountability and site-specific readiness."/><GateStep n="03" t="Field controls" b="Rain watch, first flush, collection, custody."/><GateStep n="04" t="QMS pathway" b="Applicable sample and laboratory controls."/><GateStep n="05" t="DMRV profile" b="Evidence classes and indicators remain explicit."/><GateStep n="06" t="Cross-site review" b="Compare controls, not unsupported environmental values."/><GateStep n="07" t="Exceptions" b="Deviation, CAPA and rollback remain site-scoped."/><GateStep n="08" t="Decision" b="Ready, conditional, hold or nonconforming."/></div><div className="registry-row"><div><strong>Replication invariant</strong><div className="muted">CONTROL FRAMEWORK MAY REPLICATE · EVIDENCE VALUES DO NOT</div></div><span className="badge pending-b">SITE-SCOPED</span></div><div className="scenario">ADMIN NODE ≠ HARVEST SITE · REPLICATION ≠ RELEASE · ANCHOR ≠ ENVIRONMENTAL TRUTH</div></section>}
 {conformance&&<section className="panel section control-view"><SectionTitle title="Conformance Review / S8.3" sub="Controlled pilot evidence review before replication or scale promotion."/><div className="control-banner"><div><div className="eyebrow">CURRENT GATE</div><h2>S8.3 · PILOT EVIDENCE + CONFORMANCE</h2><p>Evidence is reconciled across admission, readiness, rain event, first flush, collection, custody/QMS, DMRV, anchoring and claims. Review status cannot manufacture environmental truth.</p></div><span className="badge pending-b">REVIEW REQUIRED</span></div><div className="gate-grid"><GateStep n="01" t="Freeze scope" b="Pilot/site identity and review boundary."/><GateStep n="02" t="Reconcile field chain" b="Event → first flush → collection → custody."/><GateStep n="03" t="Review QMS" b="Methods, results, provenance and scope."/><GateStep n="04" t="Review DMRV" b="Digest, evidence classes and source provenance."/><GateStep n="05" t="Resolve conflicts" b="Material conflict → HOLD / NONCONFORMING."/><GateStep n="06" t="Review claims" b="Only claims supported by reviewed evidence."/><GateStep n="07" t="Decision" b="Conforming, nonconforming or hold."/><GateStep n="08" t="Advance" b="S8.4 only after authorized conformance decision."/></div><div className="registry-row"><div><strong>Evidence class ledger</strong><div className="muted">OBSERVED · FORECAST · MODELLED · SATELLITE · CALCULATED · PROXY</div></div><span className="badge pending-b">NO AUTOMATIC PROMOTION</span></div><div className="scenario">CONFORMANCE ≠ PREMIUM · CONFORMANCE ≠ REGULATORY APPROVAL · CONFORMANCE ≠ PRODUCT RELEASE</div></section>}
 {global&&<section className="pilot-hero panel"><div><div className="eyebrow">GLOBAL LAGOS · NIGERIA REFERENCE PILOT</div><h1>40 reporting nodes.<br/>One evidence standard.</h1><p>37 LCDA reference venues plus Governor's Office, Governor's Residence and NCF Lekki Conservation Centre. Current phase is reporting-only: no physical harvest, bottling or commercial production is represented as operational.</p><div className="actions"><button className="primary" onClick={()=>go("Evidence & DMRV")}>Inspect evidence model</button><button className="secondary" onClick={()=>go("Harvest Intelligence")}>View indicators</button><button className="secondary" onClick={()=>document.getElementById("video-port")?.scrollIntoView({behavior:"smooth"})}>Open video evidence port</button></div></div><div className="pilot-orbit"><WebGLGlobe/><span>40</span><small>NODES</small></div></section>}
 <section className="metric-grid"><Metric label="Pilot nodes" value="40" delta="37 LCDAs + 3 additional points"/><Metric label="Reference governance" value="20 / 37" delta="LGAs / LCDAs"/><Metric label="Claim integrity" value="FAIL-CLOSED" delta="Forecast ≠ measured ≠ verified"/><Metric label="Live reporting" value="GATED" delta="Provider + QA validation required"/></section>
 {global?<>
 <section className="pilot-grid"><div className="panel section"><SectionTitle title="Lagos reporting grid" sub="Click a node to inspect its evidence boundary. Coordinates remain pending until an authorized survey or authoritative GIS record exists."/><div className="venue-list">{venues.map(([a,b],i)=><Venue key={a} id={String(i+1).padStart(2,"0")} name={a} detail={b} onClick={setSelected}/>)}{institutional.map((v,i)=><Venue key={v} id={String(38+i)} name={v} detail="Institutional / environmental reference venue" onClick={setSelected} security={i===1}/>)}</div></div><div className="panel section"><SectionTitle title="Indicator source pairs" sub="Primary provider + independent cross-verification boundary"/><div className="source-cards">{indicators.map(([name,p,s,c])=><div className="source-card" key={name}><strong>{name}</strong><div><span>PRIMARY</span>{p}</div><div><span>CROSS-CHECK</span>{s}</div><em>{c}</em></div>)}</div></div></section>
 <section className="panel section" id="video-port"><SectionTitle title="Video evidence port" sub="Field-validation feed boundary · not a live harvest claim"/><div className="feed-grid">{feeds.map((f,i)=><div className="feed" key={f}><div className="feed-screen"><span>{i>2?"VIDEO":"DATA"}</span><b>{i===3?"ARCHIVE READY":"GATED"}</b></div><strong>{f}</strong><div className="muted">{i>2?"WebRTC / SRT / RTSP bridge → signed manifest → evidence root":"POLLING_API / ARCHIVE_QUERY with explicit provider provenance"}</div></div>)}</div><div className="chain">CAPTURE → TIMESTAMP → SHA-256 SEGMENT HASH → PREVIOUS-HASH LINK → MANIFEST → EVIDENCE ROOT → DMRV REVIEW</div></section>
 </>:<section className="grid"><div className="panel section"><SectionTitle title={active} sub="Institutional control surface · status-aware by design"/>{active==="Command Center"&&<Timeline/>}{active==="Harvest Intelligence"&&<Harvest/>}{active==="Evidence & DMRV"&&<DMRV/>}{active==="ESG / GHG"&&<ESG/>}{active==="Investor Room"&&<Investor/>}</div><div className="panel section"><SectionTitle title="Evidence registry" sub="Public-safe status view"/>{evidence.map(e=><div className="registry-row" key={e[0]}><div><strong>{e[0]}</strong><div className="muted">{e[1]} · {e[3]}</div></div><span className={e[2]==="VALIDATED"?"badge verified":"badge pending-b"}>{e[2]}</span></div>)}<button className="secondary full" onClick={()=>go("Evidence & DMRV")}>Inspect evidence chain</button></div></section>}
 <footer className="footer"><div className="footer-links">{[["Project Pilot","Global Lagos"],["Venues","Global Lagos"],["Indicators","Harvest Intelligence"],["Sources & DMRV","Evidence & DMRV"],["ESG / GHG","ESG / GHG"],["Investor Room","Investor Room"]].map(([x,n])=><button key={x} onClick={()=>go(n)}>{x}</button>)}</div><div>Blue-Ether OS · M-1 · P1–P20 · S4 evidence gated. REPORTABLE ≠ MEASURED ≠ VERIFIED ≠ ANCHORED.</div></footer>
 </main></div>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal panel" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">NODE {selected}</div><h2>{selectedVenue?.name}</h2></div><button className="close" onClick={()=>setSelected(null)}>×</button></div><p className="muted">{selectedVenue?.detail}</p><div className="detail-grid"><Detail k="Geo status" v={selectedVenue?.name.includes("Residence")?"GENERALIZED_PUBLIC_SITE_ONLY":"REFERENCE_ONLY"}/><Detail k="Coordinates" v="NULL · survey pending"/><Detail k="Observation" v="Provider integration gated"/><Detail k="Video" v="Field-validation only"/><Detail k="DMRV" v="Append-only evidence package"/><Detail k="Claim state" v="FAIL-CLOSED"/></div><div className="scenario">No coordinate, sensor, harvest, water-quality or verification claim is inferred from the node label.</div></div></div>}</div>
}
function Metric(p:any){return <div className="panel metric"><div className="label">{p.label}</div><div className="value">{p.value}</div><div className="delta">{p.delta}</div></div>}
function SectionTitle({title,sub}:{title:string,sub:string}){return <><h2>{title}</h2><div className="muted">{sub}</div></>}
function Venue({id,name,detail,onClick,security=false}:{id:string,name:string,detail:string,onClick:(x:string)=>void,security?:boolean}){return <button className="venue" onClick={()=>onClick(id)}><span className="node">{id}</span><div><strong>{name}</strong><div className="muted">{detail}</div></div><span className="badge pending-b">{security?"SECURITY-GATED":"GEO · PENDING"}</span></button>}
function Timeline(){return <div className="timeline">{gates.map((g,i)=><div className="step" key={g}><span className={i<8?"dot":"dot pending"}></span><div style={{flex:1}}><strong>{g}</strong><div className="muted">{i<8?"Core boundary implemented":"Review / external evidence required"}</div></div><span className={i<8?"badge verified":"badge pending-b"}>{i<8?"IMPLEMENTED":"PENDING"}</span></div>)}</div>}
function Harvest(){return <div className="cards"><Card t="Forecast snapshots" b="Provider, retrieval time, coordinates and source identity are preserved; forecast is never promoted to observation."/><Card t="Measured telemetry" b="Authorized instruments can reconcile observations against forecast skill without overwriting source records."/><Card t="Indicator registry" b="Rainfall, NO₂, SO₂, O₃, CO, PM and radiation each have primary and cross-verification boundaries."/></div>}
function DMRV(){return <div className="cards"><Card t="Immutable observation" b="Source, coordinate, timestamp, method, quality and canonical hash are retained."/><Card t="Evidence package" b="Observation + provenance + reconciliation + video manifests + event links + review state."/><Card t="Verification ladder" b="REPORTABLE → VALIDATED → VERIFIED → ANCHORED, with fail-closed promotion rules."/><Card t="Video cryptography" b="SHA-256 segment hashes, previous-hash links, signed manifests and evidence roots provide tamper-evident provenance."/><Card t="Corrections" b="Corrections create linked successor records. Original observations are never overwritten."/><Card t="Public / investor" b="Sanitized verification view exposes provenance and status without credentials or security-sensitive coordinates."/></div>}
function ESG(){return <div className="cards"><Card t="Environmental" b="Rainfall, air quality, heat, humidity, wind, solar and future measured water-quality evidence."/><Card t="Social" b="Participation, access, public benefit and operational safeguards become reportable only when evidenced."/><Card t="Governance" b="Authorization, custody, review, security and evidence integrity are explicit controls."/><Card t="GHG" b="Activity data, emission factor, scope, methodology and uncertainty remain distinct from observations."/><Card t="Regulatory" b="Regulatory evidence is an independent review layer, not implied by an environmental feed."/><Card t="Uncertainty" b="Every derived impact claim must disclose method, inputs, uncertainty and review state."/></div>}
function Investor(){return <><div className="cards"><Card t="Technical diligence" b="Architecture, tests, threat boundaries, immutable schemas and provider contracts."/><Card t="Operational diligence" b="40-node Lagos design, site authorization, geotag, instrumentation, QMS and field-validation pathway."/><Card t="Impact diligence" b="ESG/GHG methodology, assumptions, uncertainty and verification pathway."/></div><div className="bar"><i style={{width:"62%"}}/></div><div className="muted note">Illustrative diligence progress only — not an investment readiness certification.</div></>}
function Card({t,b}:{t:string,b:string}){return <div className="mini"><strong>{t}</strong><span>{b}</span></div>}
function GateStep({n,t,b}:{n:string,t:string,b:string}){return <div className="mini gate-step"><span>{n}</span><strong>{t}</strong><span>{b}</span></div>}
function Detail({k,v}:{k:string,v:string}){return <div className="detail"><span>{k}</span><strong>{v}</strong></div>}
