"use client";
import { useMemo, useState } from "react";
import WebGLGlobe from "./components/WebGLGlobe";
import { lagosNodes } from "./global-lagos/nodes";

const nav=["Command Center","Global Lagos","Harvest Intelligence","Evidence & DMRV","ESG / GHG","Investor Room"];
const gates=["Source registry","Forecast snapshot","Measured telemetry","Rain event","Collection + first flush","Water/QMS","Batch + bottle seal","Evidence root","DMRV review","Blockchain proof"];
const indicators=[
 ["Rainfall","Open-Meteo","Authorized local gauge","FORECAST ↔ OBSERVED"],["Atmospheric NO₂","CAMS/Open-Meteo","Sentinel-5P / TROPOMI","MODEL ↔ SATELLITE"],["SO₂ / O₃ / CO","CAMS/Open-Meteo","Sentinel-5P / TROPOMI","MODEL ↔ SATELLITE"],["PM2.5 / PM10","Air-quality model","Authorized local sensor","MODEL ↔ OBSERVED"],["Temperature / humidity / wind","Open-Meteo","Authorized local station","MODEL ↔ OBSERVED"],["Solar radiation","Open-Meteo","Satellite-derived dataset","MODEL ↔ SATELLITE"]
];
const evidence=[
 ["BE-OMI-0001","Rainfall observation","VALIDATED","Open-Meteo · provenance complete","ANCHOR PENDING"],["BE-OMI-0002","Atmospheric NO₂","REPORTABLE","Model + Sentinel cross-check","REVIEW REQUIRED"],["BE-OMI-0003","Controlled scenario","SIMULATED","Model-only demonstration","NOT PRODUCTION"],["VID-GL-0001","Collection video manifest","UNVERIFIED","Future field-validation boundary","NOT ANCHORED"]
];
const feeds=["Rainfall telemetry","Air-quality observations","Satellite cross-checks","Harvest operation video","Post-collection custody video"];

export default function Home(){
 const [active,setActive]=useState("Command Center"); const [demo,setDemo]=useState(false); const [selected,setSelected]=useState<string|null>(null); const global=active==="Global Lagos";
 const selectedVenue=useMemo(()=>selected?lagosNodes.find(v=>v.id===selected):null,[selected]);
 const go=(n:string)=>{setActive(n);window.scrollTo({top:0,behavior:"smooth"})};
 return <div className="shell">
 <header className="topbar"><div className="brand"><div className="mark">B</div><div>BLUE-ETHER <span>OS</span></div></div><div className="top-actions"><button className={global?"top-link active":"top-link"} onClick={()=>go("Global Lagos")}>◎ Global Lagos</button><div className="status">M-1 · S4 GATED · EVIDENCE-FIRST</div></div></header>
 <div className="layout"><aside className="nav">{nav.map(n=><button key={n} className={active===n?"active":""} onClick={()=>go(n)}>{n}</button>)}</aside><main className="main">
 {!global&&<section className="hero"><div className="panel hero-copy"><div className="eyebrow">37-LCDA WATER + ENVIRONMENTAL DATA OPERATING SYSTEM</div><h1>Rain becomes an investable evidence stream.</h1><p>Blue-Ether OS turns environmental observations into provenance-rich evidence packages. Forecasts, models, satellite observations and measured data remain explicitly distinct until their quality and reconciliation rules are satisfied.</p><div className="actions"><button className="primary" onClick={()=>go("Global Lagos")}>Explore Global Lagos Pilot</button><button className="secondary" onClick={()=>setDemo(!demo)}>{demo?"Hide controlled scenario":"Run controlled scenario"}</button><button className="secondary" onClick={()=>go("Investor Room")}>Open investor room</button></div>{demo&&<div className="scenario">CONTROLLED SIMULATION · Source → observation → QA → evidence root. No live production, harvest or sale claim.</div>}</div><div className="panel globe"><WebGLGlobe/><div className="globe-overlay"><span className="badge verified">WEBGL · VISUALIZATION</span><div><strong>Lagos environmental evidence surface</strong><div className="muted">Visualization is not evidence. Authoritative status comes from immutable evidence records.</div></div></div></div></section>}
 {global&&<section className="pilot-hero panel"><div><div className="eyebrow">GLOBAL LAGOS · NIGERIA REFERENCE PILOT</div><h1>40 reporting nodes.<br/>One evidence standard.</h1><p>37 LCDA reference venues plus Governor's Office, Governor's Residence and NCF Lekki Conservation Centre. Current phase is reporting-only: no physical harvest, bottling or commercial production is represented as operational.</p><div className="actions"><button className="primary" onClick={()=>go("Evidence & DMRV")}>Inspect evidence model</button><button className="secondary" onClick={()=>go("Harvest Intelligence")}>View indicators</button><button className="secondary" onClick={()=>document.getElementById("video-port")?.scrollIntoView({behavior:"smooth"})}>Open video evidence port</button></div></div><div className="pilot-orbit"><WebGLGlobe/><span>40</span><small>NODES</small></div></section>}
 <section className="metric-grid"><Metric label="Pilot nodes" value="40" delta="37 LCDAs + 3 additional points"/><Metric label="Reference governance" value="20 / 37" delta="LGAs / LCDAs"/><Metric label="Claim integrity" value="FAIL-CLOSED" delta="Forecast ≠ measured ≠ verified"/><Metric label="Live reporting" value="GATED" delta="Provider + QA validation required"/></section>
 {global?<>
 <section className="node-reporting"><div className="panel section"><SectionTitle title="40-node Lagos reporting surface" sub="Every node is a scroll-reporting unit. Public web imagery is visual validation only; candidate coordinates never become authorized site coordinates automatically."/><div className="node-slides">{lagosNodes.map((node,i)=><article className="node-slide" key={node.id} id={`node-${node.id}`}><div className="node-slide-index">{String(i+1).padStart(2,"0")} / 40</div><div className="node-slide-main"><div className="eyebrow">{node.class.replaceAll("_"," ")} · {node.parentLga || "STATE / ENVIRONMENT"}</div><h3>{node.name}</h3><p className="muted">{node.jurisdictionReference}</p><div className="node-landmark"><span>LANDMARK / JURISDICTION ANCHOR</span><strong>{node.landmark}</strong></div><div className="node-status-row"><span className={`badge ${node.coordinateStatus==="CANDIDATE_PUBLIC_REFERENCE"?"verified":"pending-b"}`}>{node.coordinateStatus==="CANDIDATE_PUBLIC_REFERENCE"?"CANDIDATE COORDINATE":"GIS PENDING"}</span><span className="badge pending-b">{node.evidenceState}</span></div><div className="node-actions"><a className="secondary" href={`https://www.google.com/search?tbm=isch&q=${encodeURIComponent(node.visualQuery)}`} target="_blank" rel="noreferrer">Open online visuals</a>{node.candidateCoordinates&&<a className="secondary" href={`https://www.openstreetmap.org/?mlat=${node.candidateCoordinates.latitude}&mlon=${node.candidateCoordinates.longitude}#map=17/${node.candidateCoordinates.latitude}/${node.candidateCoordinates.longitude}`} target="_blank" rel="noreferrer">Inspect map candidate</a>}</div></div><div className="node-visual"><div className="visual-placeholder"><span>ONLINE VISUAL REFERENCE</span><strong>{node.visualQuery}</strong><small>Image / street / map validation surface · not environmental evidence</small></div>{node.candidateCoordinates&&<div className="coords">Candidate WGS84 · {node.candidateCoordinates.latitude.toFixed(5)}, {node.candidateCoordinates.longitude.toFixed(5)}</div>}<div className="live-port">PUBLIC VISUAL FEED · <b>{node.liveVisualMode}</b></div></div></article>)}</div></div><div className="panel section sticky-node-index"><SectionTitle title="Node index" sub="Jump to any reporting slide"/><div className="node-index">{lagosNodes.map((node,i)=><a key={node.id} href={`#node-${node.id}`}><span>{String(i+1).padStart(2,"0")}</span>{node.name}</a>)}</div></div></section>
 <section className="panel section" id="video-port"><SectionTitle title="Video evidence port" sub="Field-validation feed boundary · not a live harvest claim"/><div className="feed-grid">{feeds.map((f,i)=><div className="feed" key={f}><div className="feed-screen"><span>{i>2?"VIDEO":"DATA"}</span><b>{i===3?"ARCHIVE READY":"GATED"}</b></div><strong>{f}</strong><div className="muted">{i>2?"WebRTC / SRT / RTSP bridge → signed manifest → evidence root":"POLLING_API / ARCHIVE_QUERY with explicit provider provenance"}</div></div>)}</div><div className="chain">CAPTURE → TIMESTAMP → SHA-256 SEGMENT HASH → PREVIOUS-HASH LINK → MANIFEST → EVIDENCE ROOT → DMRV REVIEW</div></section>
 </>:<section className="grid"><div className="panel section"><SectionTitle title={active} sub="Institutional control surface · status-aware by design"/>{active==="Command Center"&&<Timeline/>}{active==="Harvest Intelligence"&&<Harvest/>}{active==="Evidence & DMRV"&&<DMRV/>}{active==="ESG / GHG"&&<ESG/>}{active==="Investor Room"&&<Investor/>}</div><div className="panel section"><SectionTitle title="Evidence registry" sub="Public-safe status view"/>{evidence.map(e=><div className="registry-row" key={e[0]}><div><strong>{e[0]}</strong><div className="muted">{e[1]} · {e[3]}</div></div><span className={e[2]==="VALIDATED"?"badge verified":"badge pending-b"}>{e[2]}</span></div>)}<button className="secondary full" onClick={()=>go("Evidence & DMRV")}>Inspect evidence chain</button></div></section>}
 <footer className="footer"><div className="footer-links">{[["Project Pilot","Global Lagos"],["Venues","Global Lagos"],["Indicators","Harvest Intelligence"],["Sources & DMRV","Evidence & DMRV"],["ESG / GHG","ESG / GHG"],["Investor Room","Investor Room"]].map(([x,n])=><button key={x} onClick={()=>go(n)}>{x}</button>)}</div><div>Blue-Ether OS · M-1 · P1–P20 · S4 evidence gated. REPORTABLE ≠ MEASURED ≠ VERIFIED ≠ ANCHORED.</div></footer>
 </main></div>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="modal panel" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><div className="eyebrow">NODE {selected}</div><h2>{selectedVenue?.name}</h2></div><button className="close" onClick={()=>setSelected(null)}>×</button></div><p className="muted">{selectedVenue?.jurisdictionReference}</p><div className="detail-grid"><Detail k="Geo status" v={selectedVenue?.name.includes("Residence")?"GENERALIZED_PUBLIC_SITE_ONLY":"REFERENCE_ONLY"}/><Detail k="Coordinates" v="NULL · survey pending"/><Detail k="Observation" v="Provider integration gated"/><Detail k="Video" v="Field-validation only"/><Detail k="DMRV" v="Append-only evidence package"/><Detail k="Claim state" v="FAIL-CLOSED"/></div><div className="scenario">No coordinate, sensor, harvest, water-quality or verification claim is inferred from the node label.</div></div></div>}</div>
}
function Metric(p:any){return <div className="panel metric"><div className="label">{p.label}</div><div className="value">{p.value}</div><div className="delta">{p.delta}</div></div>}
function SectionTitle({title,sub}:{title:string,sub:string}){return <><h2>{title}</h2><div className="muted">{sub}</div></>}

function Timeline(){return <div className="timeline">{gates.map((g,i)=><div className="step" key={g}><span className={i<8?"dot":"dot pending"}></span><div style={{flex:1}}><strong>{g}</strong><div className="muted">{i<8?"Core boundary implemented":"Review / external evidence required"}</div></div><span className={i<8?"badge verified":"badge pending-b"}>{i<8?"IMPLEMENTED":"PENDING"}</span></div>)}</div>}
function Harvest(){return <div className="cards"><Card t="Forecast snapshots" b="Provider, retrieval time, coordinates and source identity are preserved; forecast is never promoted to observation."/><Card t="Measured telemetry" b="Authorized instruments can reconcile observations against forecast skill without overwriting source records."/><Card t="Indicator registry" b="Rainfall, NO₂, SO₂, O₃, CO, PM and radiation each have primary and cross-verification boundaries."/></div>}
function DMRV(){return <div className="cards"><Card t="Immutable observation" b="Source, coordinate, timestamp, method, quality and canonical hash are retained."/><Card t="Evidence package" b="Observation + provenance + reconciliation + video manifests + event links + review state."/><Card t="Verification ladder" b="REPORTABLE → VALIDATED → VERIFIED → ANCHORED, with fail-closed promotion rules."/><Card t="Video cryptography" b="SHA-256 segment hashes, previous-hash links, signed manifests and evidence roots provide tamper-evident provenance."/><Card t="Corrections" b="Corrections create linked successor records. Original observations are never overwritten."/><Card t="Public / investor" b="Sanitized verification view exposes provenance and status without credentials or security-sensitive coordinates."/></div>}
function ESG(){return <div className="cards"><Card t="Environmental" b="Rainfall, air quality, heat, humidity, wind, solar and future measured water-quality evidence."/><Card t="Social" b="Participation, access, public benefit and operational safeguards become reportable only when evidenced."/><Card t="Governance" b="Authorization, custody, review, security and evidence integrity are explicit controls."/><Card t="GHG" b="Activity data, emission factor, scope, methodology and uncertainty remain distinct from observations."/><Card t="Regulatory" b="Regulatory evidence is an independent review layer, not implied by an environmental feed."/><Card t="Uncertainty" b="Every derived impact claim must disclose method, inputs, uncertainty and review state."/></div>}
function Investor(){return <><div className="cards"><Card t="Technical diligence" b="Architecture, tests, threat boundaries, immutable schemas and provider contracts."/><Card t="Operational diligence" b="40-node Lagos design, site authorization, geotag, instrumentation, QMS and field-validation pathway."/><Card t="Impact diligence" b="ESG/GHG methodology, assumptions, uncertainty and verification pathway."/></div><div className="bar"><i style={{width:"62%"}}/></div><div className="muted note">Illustrative diligence progress only — not an investment readiness certification.</div></>}
function Card({t,b}:{t:string,b:string}){return <div className="mini"><strong>{t}</strong><span>{b}</span></div>}
function Detail({k,v}:{k:string,v:string}){return <div className="detail"><span>{k}</span><strong>{v}</strong></div>}
