export type LagosNode = {
  id: string;
  name: string;
  parentLga: string | null;
  class: "LCDA_REFERENCE" | "STATE_INSTITUTION" | "ENVIRONMENTAL_REFERENCE";
  jurisdictionReference: string;
  landmark: string;
  candidateCoordinates: { latitude: number; longitude: number } | null;
  coordinateStatus: "CANDIDATE_PUBLIC_REFERENCE" | "PENDING_AUTHORIZED_GIS";
  visualQuery: string;
  liveVisualMode: "PUBLIC_WEB_REFERENCE" | "GENERALIZED_SITE_VIEW";
  evidenceState: "VISUAL_REFERENCE_ONLY" | "SITE_GIS_PENDING";
};

export const lagosNodes: LagosNode[] = [
  {id:"LGA01-LCDA01",name:"Orile-Agege LCDA",parentLga:"Agege",class:"LCDA_REFERENCE",jurisdictionReference:"Orile-Agege LCDA Secretariat, Lagos",landmark:"Orile-Agege LCDA Secretariat / 2 Arigbanla Street",candidateCoordinates:{latitude:6.62599,longitude:3.3054},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Orile-Agege LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA02-LCDA01",name:"Ifelodun LCDA",parentLga:"Ajeromi-Ifelodun",class:"LCDA_REFERENCE",jurisdictionReference:"Ifelodun LCDA Secretariat, Mosafejo, Amukoko",landmark:"Ifelodun LCDA Secretariat / 3 Dispensary Street",candidateCoordinates:{latitude:6.46,longitude:3.34},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Ifelodun LCDA Secretariat Amukoko Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA03-LCDA01",name:"Ayobo-Ipaja LCDA",parentLga:"Alimosho",class:"LCDA_REFERENCE",jurisdictionReference:"Ayobo-Ipaja LCDA Secretariat, Lagos",landmark:"Ayobo Road / LCDA Secretariat area",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Ayobo-Ipaja LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA03-LCDA02",name:"Egbe-Idimu LCDA",parentLga:"Alimosho",class:"LCDA_REFERENCE",jurisdictionReference:"Egbe-Idimu LCDA Secretariat, Lagos",landmark:"Egbe / Idimu civic centre area",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Egbe-Idimu LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA03-LCDA03",name:"Igando-Ikotun LCDA",parentLga:"Alimosho",class:"LCDA_REFERENCE",jurisdictionReference:"Ikotun Secretariat Complex, close to Ikotun Market",landmark:"Ikotun Secretariat Complex / Idimu Road",candidateCoordinates:{latitude:6.54,longitude:3.26},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Igando-Ikotun LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA03-LCDA04",name:"Mosan-Okunola LCDA",parentLga:"Alimosho",class:"LCDA_REFERENCE",jurisdictionReference:"Mosan-Okunola LCDA Secretariat, Lagos",landmark:"Mosalasi / Council Road / Water Bus Stop",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Mosan-Okunola LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA04-LCDA01",name:"Oriade LCDA",parentLga:"Amuwo-Odofin",class:"LCDA_REFERENCE",jurisdictionReference:"Oriade LCDA Secretariat, Satellite Town",landmark:"Oriade LCDA / Marwa Road / Finiger Bustop",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Oriade LCDA Secretariat Satellite Town Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA05-LCDA01",name:"Apapa-Iganmu LCDA",parentLga:"Apapa",class:"LCDA_REFERENCE",jurisdictionReference:"Apapa-Iganmu LCDA Secretariat, Apapa",landmark:"Apapa-Iganmu civic/secretariat area",candidateCoordinates:{latitude:6.4481,longitude:3.3591},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Apapa-Iganmu LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA06-LCDA01",name:"Badagry West LCDA",parentLga:"Badagry",class:"LCDA_REFERENCE",jurisdictionReference:"Badagry West LCDA Secretariat / Seme axis",landmark:"Seme border / Badagry West civic area",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Badagry West LCDA Secretariat Seme Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA06-LCDA02",name:"Olorunda LCDA",parentLga:"Badagry",class:"LCDA_REFERENCE",jurisdictionReference:"Olorunda LCDA Secretariat, Lagos",landmark:"Olorunda civic area / Badagry axis",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Olorunda LCDA Secretariat Badagry Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA07-LCDA01",name:"Eredo LCDA",parentLga:"Epe",class:"LCDA_REFERENCE",jurisdictionReference:"Eredo LCDA Secretariat, Lagos",landmark:"Eredo community / Epe historic corridor",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Eredo LCDA Secretariat Epe Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA07-LCDA02",name:"Ikosi-Ejinrin LCDA",parentLga:"Epe",class:"LCDA_REFERENCE",jurisdictionReference:"Ikosi-Ejinrin LCDA Secretariat, Ejinrin",landmark:"Ejinrin / Agbowa civic corridor",candidateCoordinates:{latitude:6.53,longitude:3.85},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Ikosi-Ejinrin LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA08-LCDA01",name:"Eti-Osa East LCDA",parentLga:"Eti-Osa",class:"LCDA_REFERENCE",jurisdictionReference:"52 Lekki-Epe Expressway, Sangotedo",landmark:"Eti-Osa East Secretariat / Sangotedo",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Eti-Osa East LCDA Secretariat Sangotedo Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA08-LCDA02",name:"Iru-Victoria Island LCDA",parentLga:"Eti-Osa",class:"LCDA_REFERENCE",jurisdictionReference:"Iru-VI LCDA Secretariat, Victoria Island",landmark:"1 Muri Okunola Street / Victoria Island",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Iru Victoria Island LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA08-LCDA03",name:"Ikoyi-Obalende LCDA",parentLga:"Eti-Osa",class:"LCDA_REFERENCE",jurisdictionReference:"Ikoyi-Obalende LCDA, Lagos",landmark:"Ikoyi / Obalende civic corridor",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Ikoyi-Obalende LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA09-LCDA01",name:"Lekki LCDA",parentLga:"Ibeju-Lekki",class:"LCDA_REFERENCE",jurisdictionReference:"Lekki LCDA Secretariat, Lekki Free Zone",landmark:"Lekki Free Zone / Eleko coastal corridor",candidateCoordinates:{latitude:6.45,longitude:3.95},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Lekki LCDA Secretariat Lekki Free Zone Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA10-LCDA01",name:"Ojokoro LCDA",parentLga:"Ifako-Ijaiye",class:"LCDA_REFERENCE",jurisdictionReference:"Ojokoro LCDA Secretariat / Ijaiye-Ojokoro",landmark:"9/11 Asiwaju Bola Ahmed Way, Ijaiye Ojokoro",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Ojokoro LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA10-LCDA02",name:"Agbado-Oke-Odo LCDA",parentLga:"Ifako-Ijaiye",class:"LCDA_REFERENCE",jurisdictionReference:"Agbado-Oke-Odo LCDA Secretariat, Lagos",landmark:"Agbado / Oke-Odo civic corridor",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Agbado Oke-Odo LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA11-LCDA01",name:"Ojodu LCDA",parentLga:"Ikeja",class:"LCDA_REFERENCE",jurisdictionReference:"1–3 Secretariat Road, Oke-Ira, Ogba",landmark:"Ojodu Secretariat / Oke-Ira",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Ojodu LCDA Secretariat Oke-Ira Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA11-LCDA02",name:"Onigbongbo LCDA",parentLga:"Ikeja",class:"LCDA_REFERENCE",jurisdictionReference:"Onigbongbo LCDA Secretariat, Lagos",landmark:"Onigbongbo civic corridor",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Onigbongbo LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA12-LCDA01",name:"Ikorodu North LCDA",parentLga:"Ikorodu",class:"LCDA_REFERENCE",jurisdictionReference:"Ikorodu North LCDA Secretariat, Isiu",landmark:"MJ69+5JR / Isiu",candidateCoordinates:{latitude:6.65,longitude:3.52},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Ikorodu North LCDA Secretariat Isiu Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA12-LCDA02",name:"Ikorodu West LCDA",parentLga:"Ikorodu",class:"LCDA_REFERENCE",jurisdictionReference:"Ikorodu West LCDA Secretariat",landmark:"Oja-Owutu / ferry-terminal corridor",candidateCoordinates:{latitude:6.61,longitude:3.49},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Ikorodu West LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA12-LCDA03",name:"Imota LCDA",parentLga:"Ikorodu",class:"LCDA_REFERENCE",jurisdictionReference:"Imota LCDA Secretariat, Imota",landmark:"MM27+3X6 / LSPWC Road / Imota",candidateCoordinates:{latitude:6.64,longitude:3.6},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Imota LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA12-LCDA04",name:"Ijede LCDA",parentLga:"Ikorodu",class:"LCDA_REFERENCE",jurisdictionReference:"Ijede LCDA Secretariat / Ijede community",landmark:"Ijede coastal/farming community",candidateCoordinates:{latitude:6.5667,longitude:3.6},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Ijede LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA12-LCDA05",name:"Igbogbo-Baiyeku LCDA",parentLga:"Ikorodu",class:"LCDA_REFERENCE",jurisdictionReference:"Igbogbo-Baiyeku LCDA Secretariat",landmark:"Igbogbo civic centre / administrative complex",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Igbogbo Baiyeku LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA13-LCDA01",name:"Ikosi-Isheri LCDA",parentLga:"Kosofe",class:"LCDA_REFERENCE",jurisdictionReference:"Ikosi-Isheri LCDA, Ikosi",landmark:"20 Ikosi Road / Ikosi-Ketu",candidateCoordinates:{latitude:6.62,longitude:3.46},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Ikosi-Isheri LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA13-LCDA02",name:"Agboyi-Ketu LCDA",parentLga:"Kosofe",class:"LCDA_REFERENCE",jurisdictionReference:"Agboyi-Ketu LCDA, Lagos",landmark:"Ketu / Agboyi community corridor",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Agboyi-Ketu LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA14-LCDA01",name:"Lagos Island East LCDA",parentLga:"Lagos Island",class:"LCDA_REFERENCE",jurisdictionReference:"Lagos Island East LCDA, Broad Street area",landmark:"42 Broad Street / historic Lagos Island",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Lagos Island East LCDA Broad Street Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA15-LCDA01",name:"Yaba LCDA",parentLga:"Lagos Mainland",class:"LCDA_REFERENCE",jurisdictionReference:"Yaba LCDA, Adekunle",landmark:"Herbert Macaulay Way / Adekunle",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Yaba LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA16-LCDA01",name:"Odi-Olowo/Ojuwoye LCDA",parentLga:"Mushin",class:"LCDA_REFERENCE",jurisdictionReference:"Odi-Olowo/Ojuwoye LCDA Secretariat, Idi-Araba",landmark:"36 Town Planning Way / Ojuwoye",candidateCoordinates:{latitude:6.515,longitude:3.35},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Odi-Olowo Ojuwoye LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA17-LCDA01",name:"Oto-Awori LCDA",parentLga:"Ojo",class:"LCDA_REFERENCE",jurisdictionReference:"Oto-Awori LCDA / Ekunpa-Shibiri area",landmark:"Oto-Awori civic / Ekunpa-Shibiri corridor",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Oto-Awori LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA17-LCDA02",name:"Iba LCDA",parentLga:"Ojo",class:"LCDA_REFERENCE",jurisdictionReference:"Iba LCDA, Lagos",landmark:"Iba community / Ojo axis",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Iba LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA18-LCDA01",name:"Bariga LCDA",parentLga:"Somolu",class:"LCDA_REFERENCE",jurisdictionReference:"19 Bawala Street, Bariga",landmark:"Bawala Street / Pedro",candidateCoordinates:{latitude:6.535,longitude:3.3947},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Bariga LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA19-LCDA01",name:"Isolo LCDA",parentLga:"Oshodi-Isolo",class:"LCDA_REFERENCE",jurisdictionReference:"Isolo LCDA Secretariat, Lagos",landmark:"Isolo civic corridor",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Isolo LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA19-LCDA02",name:"Ejigbo LCDA",parentLga:"Oshodi-Isolo",class:"LCDA_REFERENCE",jurisdictionReference:"Ejigbo LCDA Secretariat, Ejigbo",landmark:"Iyana Ejigbo / Isheri-Osun civic area",candidateCoordinates:{latitude:6.51,longitude:3.32},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Ejigbo LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"LGA20-LCDA01",name:"Coker-Aguda LCDA",parentLga:"Surulere",class:"LCDA_REFERENCE",jurisdictionReference:"Coker-Aguda LCDA Secretariat / Ishola Street",landmark:"Ishola Street / Randle Avenue corridor",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Coker-Aguda LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"SITE_GIS_PENDING"},
  {id:"LGA20-LCDA02",name:"Itire-Ikate LCDA",parentLga:"Surulere",class:"LCDA_REFERENCE",jurisdictionReference:"Itire-Ikate LCDA Secretariat, Itire",landmark:"Itire / Ijesha-Tedo civic corridor",candidateCoordinates:{latitude:6.48,longitude:3.35},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Itire-Ikate LCDA Secretariat Lagos",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"STATE-VENUE-01",name:"Lagos House / Governor's Residence",parentLga:null,class:"STATE_INSTITUTION",jurisdictionReference:"Lagos House, Marina, Lagos",landmark:"Marina public-site geography only",candidateCoordinates:null,coordinateStatus:"PENDING_AUTHORIZED_GIS",visualQuery:"Lagos House Marina Lagos Nigeria",liveVisualMode:"GENERALIZED_SITE_VIEW",evidenceState:"SITE_GIS_PENDING"},
  {id:"STATE-VENUE-02",name:"Governor's Office / State Secretariat",parentLga:null,class:"STATE_INSTITUTION",jurisdictionReference:"Lagos State Secretariat, Alausa, Ikeja",landmark:"Lagos State Secretariat / Alausa",candidateCoordinates:{latitude:6.619578,longitude:3.360282},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Lagos State Secretariat Alausa Ikeja Nigeria",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"},
  {id:"STATE-VENUE-03",name:"NCF Lekki Conservation Centre",parentLga:null,class:"ENVIRONMENTAL_REFERENCE",jurisdictionReference:"Lekki Conservation Centre, Km 19 Lekki-Epe Expressway",landmark:"Lekki Conservation Centre / canopy reserve",candidateCoordinates:{latitude:6.43639,longitude:3.53556},coordinateStatus:"CANDIDATE_PUBLIC_REFERENCE",visualQuery:"Lekki Conservation Centre Lagos Nigeria",liveVisualMode:"PUBLIC_WEB_REFERENCE",evidenceState:"VISUAL_REFERENCE_ONLY"}
];
